### ISSUE TITLE
which paper？

### ISSUE THREAD

**Issue by zhongwenkun886** [matteo1994/CUDA_ChromaKey_Advanced#2]
hi，could you please tell which paper do you refer to for this project ? thanks

**Comment by matteo1994** [comment]
Hi, I'm so sorry for the late answer.
The algorithm is based on an Advanced Chroma Key found in a book:
**Video Demystified**  _by Keith Jack_ (Chapter 7, **Digital Video Processing**, section **Luma and Chroma Keying**)

**Comment by zhongwenkun886** [comment]
Thank you very much ！
